services:
  ganache:
    image: trufflesuite/ganache
    ports:
      - 8545:8545

  truffle-migrate:
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - ganache
    volumes:
      - ./:/app
    command: ["sh", "-c", "./migrations.sh"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
     - 3000:3000
    depends_on:
      - truffle-migrate
    volumes:
      - ./build/:/app/build
    command: ["npm", "run", "dev"]
