services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        GANACHE_HOST: host.docker.internal # Required for build stage
        GANACHE_PORT: 8545
    ports:
      - "3000:3000"
    environment:
      # This url will be set in config.js
      - GANACHE_URL=http://localhost:8545
    restart: on-failure
    depends_on:
      - ganache-cli
  ganache-cli:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"