services:
  ganache:
    image: trufflesuite/ganache
    ports:
      - 8545:8545

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NETWORK_URL=http://ganache:8545
    ports:
     - 3000:3000
     - 3001:3001
    depends_on:
      - ganache
    environment:
      - ENV=development
