# Values file for the tfg-truffle-pet-shop chart
image:
  repository: 986740191892.dkr.ecr.eu-west-1.amazonaws.com/tfg-truffle-pet-shop
  tag: 2025-01-28-10-54

service:
  port: 3000

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: shared-public
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: '3000'
    external-dns.alpha.kubernetes.io/hostname: pet-shop.ajripa.click
  hosts:
    - host: pet-shop.ajripa.click
      paths:
        - path: /*
          pathType: ImplementationSpecific

volumes:
  - name: config-volume
    configMap:
      name: webapp-config

volumeMounts:
  - name: config-volume
    mountPath: /app/js/config.js
    subPath: config.js
env:
  LIVE_URL: https://ganache.ajripa.click
