# templates/migration-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-migrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      name: {{ include "chart.fullname" . }}-migrations
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Compile Truffle..."
              truffle compile

              echo "Running migrations..."
              truffle migrate --network live

              echo "Verifying deployment..."
              truffle test --network live
          env:
            - name: LIVE_URL
              value: {{ .Values.config.liveUrl }}