# templates/migration-job.yaml
# Run this job during pre-install and pre-upgrade phases
# This ensures blockchain state is ready before the application starts
# Without this, the app might start before the contracts are deployed, causing errors
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tfg-truffle-pet-shop.fullname" . }}-migrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      name: {{ include "tfg-truffle-pet-shop.fullname" . }}-migrations
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Compile Truffle..."
              truffle compile

              echo "Running migrations..."
              truffle migrate --network live

              echo "Verifying deployment..."
              truffle test --network live
          env:
            - name: LIVE_URL
              value: {{ .Values.config.liveUrl }}
          volumeMounts:
            - name: contracts
              mountPath: /build/contracts
      volumes:
        - name: contracts
          persistentVolumeClaim:
            claimName: shared-contracts