name: Pet Shop Deployment

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      ganache-cli:
        image: trufflesuite/ganache-cli
        ports:
          - "8545:8545"
        options: >
          --health-cmd="curl -s http://127.0.0.1:8545 -X POST -H 'Content-Type: application/json' -d '{\"jsonrpc\": \"2.0\", \"method\": \"eth_accounts\"}' || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tfg-pet-shop:$(date +%s) --build-arg GANACHE_HOST=ganache-cli --build-arg GANACHE_PORT=8545
